### ISSUE TITLE
Emojis in instagram text break things

### ISSUE THREAD

**Issue by domani-cclark** [jtsternberg/DsgnWrks-Instagram-Importer#15]
Awesome plugin! The only issue I encountered was with emojis in the **insta-text**. This would break and wordpress would throw 

PHP Warning:  htmlspecialchars(): Invalid multibyte sequence in argument

I got around this by running a remove emoji function before saving to the db

```
function removeEmoji($text) {

    $clean_text = "";

    // Match Emoticons
    $regexEmoticons = '/[\x{1F600}-\x{1F64F}]/u';
    $clean_text = preg_replace($regexEmoticons, '', $text);

    // Match Miscellaneous Symbols and Pictographs
    $regexSymbols = '/[\x{1F300}-\x{1F5FF}]/u';
    $clean_text = preg_replace($regexSymbols, '', $clean_text);

    // Match Transport And Map Symbols
    $regexTransport = '/[\x{1F680}-\x{1F6FF}]/u';
    $clean_text = preg_replace($regexTransport, '', $clean_text);

    return $clean_text;
}
```

I would definitely recommend implementing into the plugin!

**Comment by baptistebriel** [comment]
Hi,

A came across the same issue, but here the emojis are replaced by a question mark `?`
Any ideas how I could remove them from the title & excerpt?

Thanks!

**Comment by jtsternberg** [comment]
This is old, so I'm closing. Re-open if you are still having issues.
