### ISSUE TITLE
Adding a second instagram user, things get wonky

### ISSUE THREAD

**Issue by pmgarman** [jtsternberg/DsgnWrks-Instagram-Importer#18]
The modal/iframe pops up and has an error (gray screen with the frownyfacebrokenimage thing). Then screen redirects to the instagram auth screen for the full browser window instead of in the modal. Authorizing then works fine

This only happened to me on the second user, not the first one.

**Comment by jtsternberg** [comment]
This is old, so I'm closing. Re-open if you are still having issues.
