### ISSUE TITLE
PHP notice for invalid argument

### ISSUE THREAD

**Issue by pmgarman** [jtsternberg/DsgnWrks-Instagram-Importer#19]
`Warning: Invalid argument supplied for foreach() in .../wp-content/plugins/dsgnwrks-instagram-importer/dsgnwrks-instagram-importer.php on line 87`

**Comment by jtsternberg** [comment]
You must be using the wp.org version. Can you update to this version and try it?

**Comment by jtsternberg** [comment]
This is old, so I'm closing. Re-open if you are still having issues.
