### ISSUE TITLE
debug, crontab import

### ISSUE THREAD

**Issue by aroundmyroom** [jtsternberg/DsgnWrks-Instagram-Importer#21]
Hi
I'm using at goedemorgen365.nl the plugin for a very long time now. Today I have upgraded to Version: 1.3.3 and I think something is not working with the crontab anymore
the plugin is not importing automatically anymore (manually it does) but when it manually is imported than there is no featured image on the post

The setup is simple
I have 2 instagram users: A1 and B1 and we check on a few tags to import the image
It must check every hour to see if there is a new image and set the image as featured post.

I would like to see where it is failing (if so) and what is causing it, cause waiting 1 hour to see it is not imported is a little troublesome .. 

btw I manually exectuted
http://domain.nl/wp-admin/tools.php?page=crontrol_admin_manage_page&crontrol_message=1&crontrol_name=dsgnwrks_instagram_cron
But no debug here cause it is not updating anything yet.

What is the best way to 'fix' this?

update:
debug plugin is not working with 1.3.3.

[Mon Oct 26 13:59:44 2015] [warn] [client ip.address] mod_fcgid: stderr: PHP Fatal error:  Call to undefined method DsgnWrksInstagramDebug::filter() in /var/www/vhosts/domain.nl/httpdocs/wp-content/plugins/dsgnwrks-instagram-importer-debug/DsgnWrksInstagramDebug.class.php on line 51, referer: http://domain.nl/wp-admin/tools.php?page=dsgnwrks-instagram-importer-settings

**Comment by jtsternberg** [comment]
This is old, so I'm closing. Re-open if you are still having issues.
