### ISSUE TITLE
Save Instagram photo as post's feature image

### ISSUE THREAD

**Issue by aroundmyroom** [jtsternberg/DsgnWrks-Instagram-Importer#22]
When selecting the checkbox and save the settings the selectbox is empty again
2 users, 2x the keeps the same.
same issue applies for Auto Import feature photos

fwiw:
removed 1.3.3. and re-installed 1.2.9 (tells me 1.2.8 in wp) 
the select boxes can be set correctly and the crontab functioN (#21) is working as well
(will update to every version to see if it works)

**Comment by jtsternberg** [comment]
This is old, so I'm closing. Re-open if you are still having issues.
