### ISSUE TITLE
Cannot redeclare class

### ISSUE THREAD

**Issue by synkt** [jtsternberg/DsgnWrks-Instagram-Importer#24]
I used this plugin previously, love it.  It has stopped working for me, tested it on 5 sites (3 were fresh installs).  The error I get on attempted activation:
`Fatal error: Cannot redeclare class DsgnWrksInstagram in /var/www/clients/client0/web3/web/wp-content/plugins/DsgnWrks-Instagram-Importer-master/dsgnwrks-instagram-importer.php on line 12`

Any support is greatly appreciated.

**Comment by jnsc** [comment]
You could try to disable opcache (opcache.enable=0 in php.ini)

**Comment by jtsternberg** [comment]
Is this still an issue?
