### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by chrisaldrich** [jtsternberg/DsgnWrks-Instagram-Importer#25]
When I try to "Create a User" and "Secure Authentication with Instagram" I get the error message "There was an authorization error. Try again?"

Last week sometime I had tried setting up the importer on a fresh WP install and didn't have any problem importing about 85 past posts.  Now on my live site, I'm unable to get past authentication.

I've tried going into Instagram and deauthorizing DsgnWrks Instagram Importer in case that was the issue, but it doesn't seem to be the cause.  

The plugin seems to authorize properly and redirects to the set up page for the plugin, but throws the error. (Authenticated apps within Instagram indicates that the plugin was properly authorized.) I've also tried using a different Instagram account, but that didn't work either.

Thoughts?

**Comment by jtsternberg** [comment]
I pushed some updates today. Can you try again?

**Comment by chrisaldrich** [comment]
<a href="https://github.com/jtsternberg/DsgnWrks-Instagram-Importer/issues/25" class="u-in-reply-to"></a>Updated and works wonderfully! Thanks. (I was worried it would be worse as I've heard from colleagues that IG has been pulling developer API access  recently.) 

Given the philosophy behind this plugin and your Twitter plugin, I thought I'd take a moment to mention http://www.indiewebcamp.com which is a developer movement to assist people in owning all of their own content/data rather than relying on corporate silos/walled gardens.  Your plugins sit squarely in this philosophical area.

There is a suite of related plugins (see http://indiewebcamp.com/wordpress, http://indiewebcamp.com/WordPress/Plugins, and http://indiewebcamp.com/Getting_Started_on_WordPress) that do additional types of similar data import and improved functionality. One particular function you (and your users) may appreciate is some of the plugins in combination with a service at http://brid.gy allow one to backport comments and likes from instagram, twitter, facebook, and google+ onto one's associated post on WordPress. As an example see the comments on: http://boffosocko.com/2016/05/24/55672775/. The combination of the your plugin and some of these allow users to own all of their instagram activity outright.

If you're interested and free this weekend, they're streaming a big annual meeting from Portland http://indiewebcamp.com/2016.

**Comment by jtsternberg** [comment]
Awesome, glad it works for you. The indieweb stuff sounds pretty intriguing, I'll definitely have to check it out.
