### ISSUE TITLE
Import by hashtag: No new Instagram shots to import

### ISSUE THREAD

**Issue by jeroenlammerts** [jtsternberg/DsgnWrks-Instagram-Importer#26]
Version 1.4.0

Looks like the importer stops after having no match on the hashtag filter.
The api_url is limited to [2 results](https://github.com/jtsternberg/DsgnWrks-Instagram-Importer/blob/master/dsgnwrks-instagram-importer.php#L575). The loop to go further to the next url is in comment: [link](https://github.com/jtsternberg/DsgnWrks-Instagram-Importer/blob/master/dsgnwrks-instagram-importer.php#L580)

**Comment by jtsternberg** [comment]
This will be able to be overrided (the 2 limit, then stop) with the reimport feature, https://github.com/jtsternberg/DsgnWrks-Instagram-Importer/issues/32.

**Comment by eliawk** [comment]
i download the 1.4.1 from the repo and i don't see the reimport button. 
anyway the plugin don't work when the filter by hashtag is active.
