### ISSUE TITLE
"There was an authorization error" when trying to Authenticate User

### ISSUE THREAD

**Issue by isjackwild** [jtsternberg/DsgnWrks-Instagram-Importer#28]
I am trying to setup the DsgnWrks Instagram Importer (v 1.4.0) on a Wordpress (v 4.7 site). However when I try to authorise the account, I get the message:

'There was an authorisation error. Try again?'

If I try again, I get the same message.

On my Instagram Account, I have checked, and it does list DsgnWrks Instagram Importer as authorised.

There's no other debugging information I can find (I have installed the debugger).

**Comment by jtsternberg** [comment]
This is old, so I'm closing. Re-open if you are still having issues.
