### ISSUE TITLE
Need more Details on Video Shortcodes and **codes

### ISSUE THREAD

**Issue by wmodes** [jtsternberg/DsgnWrks-Instagram-Importer#31]
According to the updated description: 

> The new shortcode, [dsgnwrks_instagram_embed src="INSTAGRAM_MEDIA_URL"], displays your imported media as an Instagram embed (works great for video!) and finally, you can now use the tags, **insta-embed-image**, and **insta-embed-video**, in the Post Content template to save the dsgnwrks_instagram_embed shortcode to the post.

That's great news. And I can see that my instagram videos are now in my media library in two different sizes. However, when Instagram Importer imports these posts, it only features the thumbnail photo. with a link to the instagram post.

If one has an instagram account that sometimes posts photos and other times posts videos, how do you make one user profile handle both gracefully?  

My current user profile is similar to the default:

```
<p><a href="**insta-link**" target="_instagram">**insta-image**</a></p>
<p>**insta-text**[if-insta-location] -- at **insta-location**[/if-insta-location]
<a href="**insta-link**" target="_instagram">Via Instagram</a></p>
```
I would like to import both images and video, displaying whichever is appropriate, an imported image if it is an image, and wordpress embedded video if it is a video.  How do I do that?

**Comment by jtsternberg** [comment]
If you add both tags, it should output the correct shortcode. Something like:
```
    <p><a href="**insta-link**" target="_instagram">**insta-image**</a></p>
    <p>**insta-text**[if-insta-location] -- at **insta-location**[/if-insta-location]
    <a href="**insta-link**" target="_instagram">Via Instagram</a></p>
    **insta-embed-image** **insta-embed-video**
```

**Comment by wmodes** [comment]
Okay, trying it. Assuming the following:

1. If Instagram Importer finds a video it leaves **insta-image** empty. 
2. Conversely, if it finds an image rather than a video, it leaves **insta-embed-image** and **insta-embed-video** empty. 
3. My embedded html will render either way. 

Is that correct?

    <p><a href="**insta-link**" target="_instagram">**insta-image** **insta-embed-image**</a>**insta-embed-video**</p>
    <p>**insta-text**[if-insta-location] -- at **insta-location**[/if-insta-location]
    <a href="**insta-link**" target="_instagram">Via Instagram</a></p>
