### ISSUE TITLE
Auto import not auto importing

### ISSUE THREAD

**Issue by wmodes** [jtsternberg/DsgnWrks-Instagram-Importer#36]
The site: peoplesriverhistory.us

I have no problem importing when I click the Import button, but my auto import is not importing automatically. Once upon a time, it did. I have tried deleting my user and adding another, and still it does not work.

Perhaps I am missing something?

![User configuration](https://user-images.githubusercontent.com/3530502/26853176-c6b669de-4ac5-11e7-83f5-a8fe7ae3b89a.png)

![Plugin options](https://user-images.githubusercontent.com/3530502/26853202-e5a3a000-4ac5-11e7-91e2-8dae038b1eda.png)

**Comment by wmodes** [comment]
Bump.

**Comment by jtsternberg** [comment]
The auto-import feature is entirely dependent on the WordPress "cron" feature which is not the most dependable (you can google to see what I mean). Closing, as there isn't anything wrong on this end, but is a broader WordPress problem.
