### ISSUE TITLE
Error creating posts

### ISSUE THREAD

**Issue by prostoprojekt** [jtsternberg/DsgnWrks-Instagram-Importer#38]
worked perfect before 20June2017, [vers.1.4.1](url) (seems some Instagrame update been made).

from that date I constantly get Error message while importing Instagram posts (please see attached)
![untitled picture](https://user-images.githubusercontent.com/10762163/27449910-fb904aee-579a-11e7-8fc0-2946381ca130.png)

**Comment by jtsternberg** [comment]
Please check your php error log to see if there is some errors there. Also, please test by deactivating other plugins.. It's entirely possible there is a conflict.
