### ISSUE TITLE
can i ONLY show square image in wp-posts? (even if fullsize image is not square)

### ISSUE THREAD

**Issue by beckmann73** [jtsternberg/DsgnWrks-Instagram-Importer#39]
can i ONLY show square image in wp-posts (even if fullsize image is not square)?

as i am using the imported images for a masonry grid it would be great if i could only use square images. 

is there any way to tell the importer that i only want square image-sizes to use as **insta-image** ?
(i have seen that the importer allready generates a 360x360px thumb after import even if the instagram-image was not square)

**Comment by jtsternberg** [comment]
You can use [`add_image_size()`](https://developer.wordpress.org/reference/functions/add_image_size/) in your theme to create the specific sizes/crops you need, then use that [in your theme output](https://developer.wordpress.org/reference/functions/add_image_size/#using-the-new-image-sizes). It won't apply those crops to the already-imported images, so for those you'd have to use the [Regenerate Thumbnails plugin](https://wordpress.org/plugins/regenerate-thumbnails/).

The importer simply imports the full-size image, and it is up to you/your theme as to how those images are output.
