### ISSUE TITLE
Image size+quality (visible artifacts)

### ISSUE THREAD

**Issue by flegfleg** [jtsternberg/DsgnWrks-Instagram-Importer#50]
Hi, thanks for the plugin! 

Not sure this is related to the plugin itself, but the image quality (of the "original" image in WP*) is visibly worse than the online version on Instagram. Also, it does not download the original size (1080x1080), i have only 640x640-version in my library. 

<img width="661" alt="11-04-2018-00 44 29" src="https://user-images.githubusercontent.com/4009931/47958439-e6e62e00-dfcb-11e8-8ee0-155a692a362e.png">

Any idea why/how to solve this?

Thanks 

*just to be clear: i am looking at the downloaded original image in full resolution, not the thumbnails.

**Comment by jtsternberg** [comment]
The instagram API does not provide the full-resolution url for the images.

**Comment by jtsternberg** [comment]
New version should pull in higher resolutions again... until Facebook/Instagram removes that hack.

**Comment by flegfleg** [comment]
Fantastic, thanks!
